### PR TITLE
Add docker files for easier deployment

### PR DESCRIPTION
**Pull request by TheEdgeOfRage**
Just a simple Dockerfile and docker-compose.yml so that you can run myazo inside of a container.

### CODE REVIEW

**Comment by TheEdgeOfRage** [comment]
Well, there already is a volume set up in the docker-compose file. As for https I am unsure how one would go about getting the certificates inside of the container. What I do on my server is have a main nginx reverse proxy that handles connections from the internet through https and then proxies them based on the domain to the specific container using http, as communication inside the server doesn't require TLS.

**Comment by migueldemoura** [comment]
You're right about possibly not wanting to terminate the tls at this container. I pointed that out since the script has `https` hardcoded as a deterrent to using plain http. Wouldn't this confuse users?

Regarding the data volume, I meant something like this:

docker-compose.yml
```
version: "3"
services:
  [...]
  myazo:
    volumes:
      - data-myazo:/app/public/uploads

volumes:
  data-myazo:
    driver: local
```

With this approach you could also delete the `.gitignore` line as well. Let me know what you think!

**Comment by TheEdgeOfRage** [comment]
Yeah, that's a more sane default. I changed it now.

**Comment by migueldemoura** [comment]
Made just a couple of changes to match the default path settings and added a note to the README. Thanks for the PR, @TheEdgeOfRage!

**Pull request merged**
